#!/usr/bin/env python3
"""
This module provides an async function that
collects 10 random numbers and returns it
"""
from typing import List
async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    Asynchronously collects 10 random floating-point numbers
    generated by async_generator and returns them as a list.

    Returns:
        List[float]: A list containing 10 random floating-point
        numbers between 0 and 10.
    """
    result = [i async for i in async_generator()]
    return result
